### ISSUE TITLE
Order of functions in class is reverse doxygen xml output

### ISSUE THREAD

**Issue by om23** [matusnovak/doxybook2#16] opened 2020-07-18 00:51 UTC
When attempting to use the xml output from doxygen and keeping sorting off (not alphabetical, use order of declaration), the functions are not ordered in the class file. 

This is reproducible using the example Gitbook provided.

**Comment by matusnovak** [comment] 2020-07-18 09:01
Hi @om23 

Thanks for letting me know, I have found the cause of this ordering issue. I have created a fix in the branch [fix-preserve-ordering](https://github.com/matusnovak/doxybook2/compare/fix-preserve-ordering) and a binary can be downloaded from actions: https://github.com/matusnovak/doxybook2/actions/runs/173622059 (download the "Release" artifact).

Would you be able to test it out and confirm it works before I merge it into the master?

**Comment by om23** [comment] 2020-07-18 19:29
Yes, confirming that pulling the diff and applying it locally did fix the ordering issue. It now matches the output of doxygen. Thank you!

**Comment by matusnovak** [comment] 2020-07-20 20:59
Thanks for testing it. Merged and released as [releases/tag/v1.2.1](https://github.com/matusnovak/doxybook2/releases/tag/v1.2.1).

**Closed as completed by matusnovak** 2020-07-20 20:59 UTC
